# Generated by Django 4.0.3 on 2022-03-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favouriteBooks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite_books',
            name='book_name',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
